# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-30 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180530_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='summary',
            field=models.CharField(default='Summary', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('librarian', 'Librarian'), ('student', 'Student')], default='librarian', max_length=50),
        ),
    ]
