# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-08 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180530_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dept',
            field=models.CharField(default='EnTC', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.CharField(default='11/11/1997', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='Male', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='rollno',
            field=models.CharField(default='0000', max_length=50),
        ),
    ]
