# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-08 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180608_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='rating',
            new_name='genre',
        ),
    ]
