# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-08 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180608_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='summary',
            field=models.CharField(default='Summary', max_length=200),
        ),
    ]
